// <auto-generated />
using System;
using ITProjectPriceCalculationManager.EvaluatorManager.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITProjectPriceCalculationManager.EvaluatorManager.API.Migrations
{
    [DbContext(typeof(ITProjectPriceCalculationEvaluatorManagerDbContext))]
    [Migration("20240606184919_InitDataBase")]
    partial class InitDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITProjectPriceCalculationManager.EvaluatorManager.API.Core.Entities.BelongingFunction.BelongingFunction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BelongingFunction");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4bf3d51-4f18-42e5-b92f-1e8cf40dca1a"),
                            Name = "SigmoidMembershipFunction"
                        },
                        new
                        {
                            Id = new Guid("a13bcaf8-0d49-4df7-ba32-0d6fd5b4c4c0"),
                            Name = "GaussianMembershipFunction"
                        },
                        new
                        {
                            Id = new Guid("6d8622f5-8e17-49a9-b66e-5e11fd761278"),
                            Name = "ExponentialMembershipFunction"
                        },
                        new
                        {
                            Id = new Guid("9c4b86fc-0f8f-4e26-8de0-29c57b076a54"),
                            Name = "QuadraticMembershipFunction"
                        });
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.EvaluatorManager.API.Core.Entities.EvaluateParameter.EvaluateParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BelongingFunctionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParameterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParameterValueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BelongingFunctionId");

                    b.HasIndex("ParameterId");

                    b.ToTable("EvaluateParameter");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.EvaluatorManager.API.Core.Entities.ParameterValue.ParameterValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("A")
                        .HasColumnType("real");

                    b.Property<float>("B")
                        .HasColumnType("real");

                    b.Property<float>("C")
                        .HasColumnType("real");

                    b.Property<float>("D")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ParameterValue");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.EvaluatorManager.API.Core.Entities.Parameters.Parameters", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.EvaluatorManager.API.Core.Entities.EvaluateParameter.EvaluateParameter", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.EvaluatorManager.API.Core.Entities.BelongingFunction.BelongingFunction", "BelongingFunction")
                        .WithMany("EvaluateParameters")
                        .HasForeignKey("BelongingFunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITProjectPriceCalculationManager.EvaluatorManager.API.Core.Entities.Parameters.Parameters", "Parameter")
                        .WithMany("EvaluateParameters")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BelongingFunction");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.EvaluatorManager.API.Core.Entities.ParameterValue.ParameterValue", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.EvaluatorManager.API.Core.Entities.EvaluateParameter.EvaluateParameter", "EvaluateParameter")
                        .WithOne("ParameterValue")
                        .HasForeignKey("ITProjectPriceCalculationManager.EvaluatorManager.API.Core.Entities.ParameterValue.ParameterValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluateParameter");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.EvaluatorManager.API.Core.Entities.BelongingFunction.BelongingFunction", b =>
                {
                    b.Navigation("EvaluateParameters");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.EvaluatorManager.API.Core.Entities.EvaluateParameter.EvaluateParameter", b =>
                {
                    b.Navigation("ParameterValue")
                        .IsRequired();
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.EvaluatorManager.API.Core.Entities.Parameters.Parameters", b =>
                {
                    b.Navigation("EvaluateParameters");
                });
#pragma warning restore 612, 618
        }
    }
}
