version: '3.7'

services:
  ip_project_price_calculation_manager.web_app:
      build: ITProjectPriceCalculationManager.WebApp

  ip_project_price_calculation_manager.price_predictor.api:
      build: ITProjectPriceCalculationManager.PricePredictor.API

  postgres:
      image: postgres
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5100:5432'
      volumes: 
        - ./postgres-data:/var/lib/postgresql/data
        # copy the sql script to create tables
        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql