version: '3.7'

networks:
  security-net:
    driver: bridge
  security-database-net:
    driver: bridge
  evaluator-database-net:
    driver: bridge
  front-net:
    driver: bridge
  service-net:
    driver: bridge
  it_projects_manager-database-net:
    driver: bridge

volumes:
  it-projects-manager-data:
    external: false
  auth-server-data:
    external: false
  evaluator_manager-data:
    external: false
services:
  it_project_price_calculation_manager.web_app:
    image: ghcr.io/alex-knu/diplom.web_app:latest
    restart: always
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      front-net:
        aliases:
          - web_app

  # it_project_price_calculation_manager.price_predictor.api:
  #   image: ghcr.io/alex-knu/diplom.price_predictor.api
  #   restart: always
  #   build: 
  #     context: .
  #     dockerfile: ITProjectPriceCalculationManager.PricePredictor.API/Dockerfile
  #   ports:
  #     - "5004:80"
  #     - "5005:443"
  #   networks:
  #     service-net:
  #       aliases:
  #         - price_predictor.api

  it_project_price_calculation_manager.it_projects_calculator.api:
    image: ghcr.io/alex-knu/diplom.it_projects_calculator.api:latest
    restart: always
    ports:
      - "5002:80"
      - "5003:443"
    networks:
      service-net:
        aliases:
          - it_projects_calculator.api
    depends_on:
      - it_project_price_calculation_manager.postgres
    volumes:
      - $HOME/.microsoft/usersecrets/:/root/.microsoft/usersecrets/:ro

  it_project_price_calculation_manager.it_projects_manager.api:
    image: ghcr.io/alex-knu/diplom.it_projects_manager.api:latest
    restart: always
    ports:
      - "5006:80"
      - "5007:443"
    env_file:
      - ./Env/it_projects_manager_api.env
      - ./Env/jwt.env
    networks:
      it_projects_manager-database-net:
      service-net:
        aliases:
          - it_projects_manager.api
    environment:
      - "ConnectionStrings:ITProjectPriceCalculationManagerDbContext=Server=it_project_price_calculation_manager.postgres;Port=5432;Database=ITProjectPriceCalculationManager;Username=postgres;Password=postgres"
    depends_on:
      - it_project_price_calculation_manager.postgres
    volumes:
      - $HOME/.microsoft/usersecrets/:/root/.microsoft/usersecrets/:ro

  it_project_price_calculation_manager.router.api:
    image: ghcr.io/alex-knu/diplom.router.api:latest
    restart: always
    ports:
      - "5008:80"
      - "5009:443"
    env_file:
      - ./Env/router_api.env
      - ./Env/jwt.env
    networks:
      front-net:
        aliases:
          - router.api
      service-net:
        aliases:
          - router.api
    depends_on:
      - it_project_price_calculation_manager.postgres
    volumes:
      - $HOME/.microsoft/usersecrets/:/root/.microsoft/usersecrets/:ro

  it_project_price_calculation_manager.auth_server:
    image: ghcr.io/alex-knu/diplom.auth_server:latest
    restart: always
    ports:
      - "5010:80"
      - "5011:443"
    env_file:
      - ./Env/auth_server.env
      - ./Env/jwt.env
    networks:
      security-database-net:
      front-net:
        aliases:
          - auth_server
    depends_on:
      - it_project_price_calculation_manager.auth_server.postgres
    volumes:
      - $HOME/.microsoft/usersecrets/:/root/.microsoft/usersecrets/:ro

  it_project_price_calculation_manager.evaluator_manager.api:
    image: ghcr.io/alex-knu/diplom.evaluator_manager.api:latest
    restart: always
    ports:
      - "5012:80"
      - "5013:443"
    env_file:
      - ./Env/evaluator_manager_api.env
      - ./Env/jwt.env
    networks:
      evaluator-database-net:
      service-net:
        aliases:
          - evaluator_manager.api
    depends_on:
      - it_project_price_calculation_manager.evaluator_manager.postgres
    volumes:
      - $HOME/.microsoft/usersecrets/:/root/.microsoft/usersecrets/:ro

  it_project_price_calculation_manager.postgres:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@ssw0rd007"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5100:1433
    networks:
      it_projects_manager-database-net:
        aliases:
          - it_project_price_calculation_manager.postgres
    volumes:
      - it-projects-manager-data:/var/opt/mssql

  it_project_price_calculation_manager.auth_server.postgres:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@ssw0rd007"
      #MSSQL_PID: Exspress
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5101:1433
    networks:
      security-database-net:
        aliases:
          - it_project_price_calculation_manager.auth_server.postgres
    volumes:
      - auth-server-data:/var/opt/mssql


  it_project_price_calculation_manager.evaluator_manager.postgres:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@ssw0rd007"
      #MSSQL_PID: Exspress
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5102:1433
    networks:
      security-database-net:
        aliases:
          - it_project_price_calculation_manager.evaluator_manager.postgres
    volumes:
      - auth-server-data:/var/opt/mssql
