// <auto-generated />
using System;
using ITProjectPriceCalculationManager.ITProjectsManager.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITProjectPriceCalculationManager.ITProjectsManager.API.Migrations
{
    [DbContext(typeof(ITProjectPriceCalculationManagerDbContext))]
    [Migration("20230607154552_AddStoredProcedure")]
    partial class AddStoredProcedure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Application.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AverageCostLabor")
                        .HasColumnType("float");

                    b.Property<double>("AverageMonthlyRateWorkingHours")
                        .HasColumnType("float");

                    b.Property<double?>("ConfidenceArea")
                        .HasColumnType("float");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Overhead")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Profit")
                        .HasColumnType("float");

                    b.Property<double>("SocialInsurance")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ApplicationToEvaluator.ApplicationToEvaluator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("SelfEvaluation")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("EvaluatorId");

                    b.ToTable("ApplicationToEvaluators");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ApplicationToFactors.ApplicationToFactors", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DifficultyLevelsTypeToFactorTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("DifficultyLevelsTypeToFactorTypeId");

                    b.ToTable("ApplicationToFactors");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Attribute.Attribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Attributes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a0822a4-7012-4738-889b-fafb713f72ea"),
                            Name = "Qualifications(PERS)"
                        },
                        new
                        {
                            Id = new Guid("24fbf4f3-aa84-4b17-9d2e-0ef16238a2ba"),
                            Name = "Experience(PREX)"
                        },
                        new
                        {
                            Id = new Guid("33e07ded-1bd4-4e9a-8076-f071ea1a5269"),
                            Name = "Technical support(FCIL)"
                        },
                        new
                        {
                            Id = new Guid("ea5a8d97-0940-4463-b07a-d6a10b6f0d08"),
                            Name = "Schedule restrictions(SCED)"
                        },
                        new
                        {
                            Id = new Guid("fe85d6ab-ade6-412f-b2a6-7ca97f4f1da4"),
                            Name = "Complexity of the program environment(PDIF)"
                        },
                        new
                        {
                            Id = new Guid("4feab03a-7415-4c72-8b3f-6901e014c25e"),
                            Name = "Complexity and reliability(RCPX)"
                        },
                        new
                        {
                            Id = new Guid("9b7d2f14-9ec0-414c-806b-d5e607664031"),
                            Name = "Reuse requested(RUSE)"
                        },
                        new
                        {
                            Id = new Guid("15140cfd-eacc-41f3-aae5-718980da88b9"),
                            Name = "Product novelty for the developer's company(PREC)"
                        },
                        new
                        {
                            Id = new Guid("b4a2b0b2-35c4-41d4-8ca7-1d2ebd1440e9"),
                            Name = "Development flexibility(FLEX)"
                        },
                        new
                        {
                            Id = new Guid("186476d2-772b-4eb1-b140-b0c1a238ae11"),
                            Name = "Level of risk/architecture management (%)(RESL)"
                        },
                        new
                        {
                            Id = new Guid("74b32655-e330-4e74-a1a2-e1e92023f676"),
                            Name = "Cohesion of the development team(TEAM)"
                        },
                        new
                        {
                            Id = new Guid("c69edb03-4fb6-4071-bcc5-f158808c69ee"),
                            Name = "Technology maturity maturity process development(PMAT)"
                        },
                        new
                        {
                            Id = new Guid("e777b5bf-559d-4194-a711-89ca4ca4a212"),
                            Name = "Internal logical object"
                        },
                        new
                        {
                            Id = new Guid("d7c7beea-3351-482b-82e1-8df4573395b9"),
                            Name = "External interface object"
                        },
                        new
                        {
                            Id = new Guid("73a3a716-f447-4057-99ca-1500d438ba58"),
                            Name = "External input"
                        },
                        new
                        {
                            Id = new Guid("31f2f6d6-a5fa-4da3-adcf-0a5cc237eb95"),
                            Name = "External output"
                        },
                        new
                        {
                            Id = new Guid("7a540a8b-0198-40d8-9185-2e02ba5eb1ab"),
                            Name = "External request"
                        });
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Department.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.DifficultyLevels.DifficultyLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluationAttributeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RelationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationAttributeId");

                    b.ToTable("DifficultyLevels");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.DifficultyLevelsType.DifficultyLevelsType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DifficultyLevelsTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3b0177d-baf9-4ad6-b1c1-002e1b776a10"),
                            Name = "Super low"
                        },
                        new
                        {
                            Id = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            Name = "Very low"
                        },
                        new
                        {
                            Id = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            Name = "Low"
                        },
                        new
                        {
                            Id = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            Name = "Normal"
                        },
                        new
                        {
                            Id = new Guid("5540d80e-8fae-4afb-a475-b49c1a9c4c2e"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            Name = "High"
                        },
                        new
                        {
                            Id = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            Name = "Very high"
                        },
                        new
                        {
                            Id = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            Name = "Super high"
                        });
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.DifficultyLevelsTypeToFactorType.DifficultyLevelsTypeToFactorType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DifficultyLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FactorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FactorTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyLevelId");

                    b.HasIndex("FactorId");

                    b.HasIndex("FactorTypeId");

                    b.ToTable("DifficultyLevelsTypeToFactorTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("61d50613-bdfb-4ca8-b0a5-1e42b3f86ed7"),
                            DifficultyLevelId = new Guid("b3b0177d-baf9-4ad6-b1c1-002e1b776a10"),
                            FactorId = new Guid("7a0822a4-7012-4738-889b-fafb713f72ea"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 2.1200000000000001
                        },
                        new
                        {
                            Id = new Guid("fcc2cc11-6dfa-4a97-9326-34f91ded8265"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("7a0822a4-7012-4738-889b-fafb713f72ea"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.6200000000000001
                        },
                        new
                        {
                            Id = new Guid("a8e8d742-e180-494e-b9d4-8a18a183d73a"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("7a0822a4-7012-4738-889b-fafb713f72ea"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.26
                        },
                        new
                        {
                            Id = new Guid("66ba0147-4207-4f58-84e6-527635c91406"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("7a0822a4-7012-4738-889b-fafb713f72ea"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("bdce45f4-8ca8-44a1-ac60-7dadee4c172f"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("7a0822a4-7012-4738-889b-fafb713f72ea"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.82999999999999996
                        },
                        new
                        {
                            Id = new Guid("c50f6132-0a0c-4d00-bcd9-a1ed047519fc"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("7a0822a4-7012-4738-889b-fafb713f72ea"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.63
                        },
                        new
                        {
                            Id = new Guid("9a08595e-25b1-40c8-abd4-b834d7e55f0c"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("7a0822a4-7012-4738-889b-fafb713f72ea"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.5
                        },
                        new
                        {
                            Id = new Guid("e9a16436-0072-425e-a9b0-730f75bf6ce4"),
                            DifficultyLevelId = new Guid("b3b0177d-baf9-4ad6-b1c1-002e1b776a10"),
                            FactorId = new Guid("24fbf4f3-aa84-4b17-9d2e-0ef16238a2ba"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.5900000000000001
                        },
                        new
                        {
                            Id = new Guid("ee43589a-3435-4366-b376-c3b2cc253cc6"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("24fbf4f3-aa84-4b17-9d2e-0ef16238a2ba"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.3300000000000001
                        },
                        new
                        {
                            Id = new Guid("626fd42b-5467-4834-a280-09059aeb89f6"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("24fbf4f3-aa84-4b17-9d2e-0ef16238a2ba"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.1200000000000001
                        },
                        new
                        {
                            Id = new Guid("fa0471e6-10c0-45b0-9d0b-6c2aa9a66ff7"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("24fbf4f3-aa84-4b17-9d2e-0ef16238a2ba"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("37dd742a-b49f-4cb4-b4e4-0bcc161d01c1"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("24fbf4f3-aa84-4b17-9d2e-0ef16238a2ba"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.87
                        },
                        new
                        {
                            Id = new Guid("42a611e3-2164-4a7a-94bd-1d6217ca8a7e"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("24fbf4f3-aa84-4b17-9d2e-0ef16238a2ba"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.70999999999999996
                        },
                        new
                        {
                            Id = new Guid("9507ef0f-b9ef-457c-b24d-820cfc888d38"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("24fbf4f3-aa84-4b17-9d2e-0ef16238a2ba"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.62
                        },
                        new
                        {
                            Id = new Guid("b4fcbba5-8f1b-4be3-852a-7ca6dbb02b0c"),
                            DifficultyLevelId = new Guid("b3b0177d-baf9-4ad6-b1c1-002e1b776a10"),
                            FactorId = new Guid("33e07ded-1bd4-4e9a-8076-f071ea1a5269"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.4299999999999999
                        },
                        new
                        {
                            Id = new Guid("fd56539f-611e-43d3-bd01-7f45957bc762"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("33e07ded-1bd4-4e9a-8076-f071ea1a5269"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.3
                        },
                        new
                        {
                            Id = new Guid("d7274e25-0a61-4284-bf65-7498f5c269d1"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("33e07ded-1bd4-4e9a-8076-f071ea1a5269"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.1000000000000001
                        },
                        new
                        {
                            Id = new Guid("15eb8f6e-4424-442f-9d09-c17572e4ce39"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("33e07ded-1bd4-4e9a-8076-f071ea1a5269"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("0664b4ba-40b1-4dde-b911-be4c11768842"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("33e07ded-1bd4-4e9a-8076-f071ea1a5269"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.87
                        },
                        new
                        {
                            Id = new Guid("49fd07ac-c843-4c4a-8c15-af2ea046f22f"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("33e07ded-1bd4-4e9a-8076-f071ea1a5269"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.72999999999999998
                        },
                        new
                        {
                            Id = new Guid("aabc3740-1937-4514-b2fa-c98bf4df42e8"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("33e07ded-1bd4-4e9a-8076-f071ea1a5269"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.62
                        },
                        new
                        {
                            Id = new Guid("0e3963a1-8c48-4e89-83c0-8083346205e5"),
                            DifficultyLevelId = new Guid("b3b0177d-baf9-4ad6-b1c1-002e1b776a10"),
                            FactorId = new Guid("ea5a8d97-0940-4463-b07a-d6a10b6f0d08"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("ec168468-b978-4ddf-bcf4-b03485f27d2a"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("ea5a8d97-0940-4463-b07a-d6a10b6f0d08"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.4299999999999999
                        },
                        new
                        {
                            Id = new Guid("d8832943-79a3-4a79-abeb-028ae9ed7d31"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("ea5a8d97-0940-4463-b07a-d6a10b6f0d08"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.1399999999999999
                        },
                        new
                        {
                            Id = new Guid("52bbf9ea-b961-4261-8a09-49a959e3d953"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("ea5a8d97-0940-4463-b07a-d6a10b6f0d08"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("e14a55b5-dc98-4666-9462-c27b1945f555"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("ea5a8d97-0940-4463-b07a-d6a10b6f0d08"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("79619875-8c3d-44fa-a5c7-4c8c47c49407"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("ea5a8d97-0940-4463-b07a-d6a10b6f0d08"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("eab78f44-00af-4070-82a5-b2bc52772d97"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("ea5a8d97-0940-4463-b07a-d6a10b6f0d08"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("2f4c051b-b360-4c27-bb86-0b220c351453"),
                            DifficultyLevelId = new Guid("b3b0177d-baf9-4ad6-b1c1-002e1b776a10"),
                            FactorId = new Guid("fe85d6ab-ade6-412f-b2a6-7ca97f4f1da4"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("7890b077-9e00-4b85-89aa-cee38565cb39"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("fe85d6ab-ade6-412f-b2a6-7ca97f4f1da4"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("b3be8e21-aa07-4773-b65f-1980c0dc3e03"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("fe85d6ab-ade6-412f-b2a6-7ca97f4f1da4"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.87
                        },
                        new
                        {
                            Id = new Guid("23100109-5b23-4e55-b3b0-451bece79a31"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("fe85d6ab-ade6-412f-b2a6-7ca97f4f1da4"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("51be920e-b076-4b08-ab71-8b60476a2169"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("fe85d6ab-ade6-412f-b2a6-7ca97f4f1da4"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.29
                        },
                        new
                        {
                            Id = new Guid("c55ceaf7-31de-49e0-9a17-74d5b3cebb1a"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("fe85d6ab-ade6-412f-b2a6-7ca97f4f1da4"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.8100000000000001
                        },
                        new
                        {
                            Id = new Guid("0f57ef6d-7068-4e83-b2c4-ff456224bd67"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("fe85d6ab-ade6-412f-b2a6-7ca97f4f1da4"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 2.6099999999999999
                        },
                        new
                        {
                            Id = new Guid("74a91eda-82c6-4cbc-9941-05d33fe8bd24"),
                            DifficultyLevelId = new Guid("b3b0177d-baf9-4ad6-b1c1-002e1b776a10"),
                            FactorId = new Guid("4feab03a-7415-4c72-8b3f-6901e014c25e"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.48999999999999999
                        },
                        new
                        {
                            Id = new Guid("dade7ff2-04b8-45bb-91f4-3aba16352918"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("4feab03a-7415-4c72-8b3f-6901e014c25e"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.59999999999999998
                        },
                        new
                        {
                            Id = new Guid("9398626d-741f-4607-8bfa-47822727cf36"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("4feab03a-7415-4c72-8b3f-6901e014c25e"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.82999999999999996
                        },
                        new
                        {
                            Id = new Guid("2e3cc07d-be0c-4976-a95b-7aaba860bae4"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("4feab03a-7415-4c72-8b3f-6901e014c25e"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("59bd520e-d8cd-4cf7-b69e-34cf756c9776"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("4feab03a-7415-4c72-8b3f-6901e014c25e"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.3300000000000001
                        },
                        new
                        {
                            Id = new Guid("69062e8b-3553-4b0e-8f77-f49c32f33a5d"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("4feab03a-7415-4c72-8b3f-6901e014c25e"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.97
                        },
                        new
                        {
                            Id = new Guid("16aab2a9-9185-49ff-af27-8c07d9973189"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("4feab03a-7415-4c72-8b3f-6901e014c25e"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 2.7200000000000002
                        },
                        new
                        {
                            Id = new Guid("cda37352-0b28-4626-8e61-e9722449619a"),
                            DifficultyLevelId = new Guid("b3b0177d-baf9-4ad6-b1c1-002e1b776a10"),
                            FactorId = new Guid("9b7d2f14-9ec0-414c-806b-d5e607664031"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("51abbe58-6f21-4486-9f34-7b09ca81acdd"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("9b7d2f14-9ec0-414c-806b-d5e607664031"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("ad41ef58-9411-4f70-b92f-f3445943a505"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("9b7d2f14-9ec0-414c-806b-d5e607664031"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.94999999999999996
                        },
                        new
                        {
                            Id = new Guid("3d00689d-c780-487d-872e-aba20588251d"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("9b7d2f14-9ec0-414c-806b-d5e607664031"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("9ee2abc1-a2be-4d4d-8fb8-bc8f61e13629"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("9b7d2f14-9ec0-414c-806b-d5e607664031"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0700000000000001
                        },
                        new
                        {
                            Id = new Guid("d7762f21-783d-4730-89ac-24ffcc9c4f77"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("9b7d2f14-9ec0-414c-806b-d5e607664031"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.1499999999999999
                        },
                        new
                        {
                            Id = new Guid("1fae9c5d-f8ef-4b46-ada2-1fc907e76b65"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("9b7d2f14-9ec0-414c-806b-d5e607664031"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.24
                        },
                        new
                        {
                            Id = new Guid("b92839bc-85ca-4e77-a56b-2c520ab2b5b4"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("15140cfd-eacc-41f3-aae5-718980da88b9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 6.2000000000000002
                        },
                        new
                        {
                            Id = new Guid("1a0934c7-cf96-47f2-b7d0-69d91d95569b"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("15140cfd-eacc-41f3-aae5-718980da88b9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 4.96
                        },
                        new
                        {
                            Id = new Guid("22c4de16-15b5-4ead-82ab-0ee96b9bf69d"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("15140cfd-eacc-41f3-aae5-718980da88b9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 3.7200000000000002
                        },
                        new
                        {
                            Id = new Guid("9c8651bb-9852-4900-9b33-8d70bccd4f71"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("15140cfd-eacc-41f3-aae5-718980da88b9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 2.48
                        },
                        new
                        {
                            Id = new Guid("85e0b09d-82a3-4dfe-af59-a7504619dc04"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("15140cfd-eacc-41f3-aae5-718980da88b9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 1.24
                        },
                        new
                        {
                            Id = new Guid("1efa35ef-6c6a-4d5e-a19a-0a2310ed621a"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("15140cfd-eacc-41f3-aae5-718980da88b9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("011e89ff-b436-4027-a25a-867a0159ee5a"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("b4a2b0b2-35c4-41d4-8ca7-1d2ebd1440e9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 5.0700000000000003
                        },
                        new
                        {
                            Id = new Guid("f82a6440-357e-47b7-92a0-97d09a1966da"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("b4a2b0b2-35c4-41d4-8ca7-1d2ebd1440e9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 4.0499999999999998
                        },
                        new
                        {
                            Id = new Guid("da02c0d4-4fc6-4cd8-9a6d-c94e8be95954"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("b4a2b0b2-35c4-41d4-8ca7-1d2ebd1440e9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 3.04
                        },
                        new
                        {
                            Id = new Guid("c0252b34-9b51-4c71-8606-300c71c49fa5"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("b4a2b0b2-35c4-41d4-8ca7-1d2ebd1440e9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 2.0299999999999998
                        },
                        new
                        {
                            Id = new Guid("86d97478-ec05-4bde-8b1f-e6b95bc09a67"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("b4a2b0b2-35c4-41d4-8ca7-1d2ebd1440e9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 1.01
                        },
                        new
                        {
                            Id = new Guid("a1e5d124-36ea-48a2-b31a-5ab6834b6cf3"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("b4a2b0b2-35c4-41d4-8ca7-1d2ebd1440e9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("66e20008-20e4-473f-bff3-39b867529bb1"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("186476d2-772b-4eb1-b140-b0c1a238ae11"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 7.0700000000000003
                        },
                        new
                        {
                            Id = new Guid("f5a23ad8-1f6a-4509-b6eb-264f5a23a76a"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("186476d2-772b-4eb1-b140-b0c1a238ae11"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 5.6500000000000004
                        },
                        new
                        {
                            Id = new Guid("45a4a0f3-8666-44ec-aebe-e97c75365dad"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("186476d2-772b-4eb1-b140-b0c1a238ae11"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 4.2400000000000002
                        },
                        new
                        {
                            Id = new Guid("ab7f6072-2447-4951-a5dd-11041f880df3"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("186476d2-772b-4eb1-b140-b0c1a238ae11"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 2.8300000000000001
                        },
                        new
                        {
                            Id = new Guid("d8e96327-76c7-49af-9199-fe82c37c5cbd"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("186476d2-772b-4eb1-b140-b0c1a238ae11"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 1.4099999999999999
                        },
                        new
                        {
                            Id = new Guid("61554039-7c2e-4641-94a1-5eaff5c53c33"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("186476d2-772b-4eb1-b140-b0c1a238ae11"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("c880ff2f-c9db-44c4-b626-75b445f090b9"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("74b32655-e330-4e74-a1a2-e1e92023f676"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 5.4800000000000004
                        },
                        new
                        {
                            Id = new Guid("00ed3585-d320-4252-9d9f-326ef932aab1"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("74b32655-e330-4e74-a1a2-e1e92023f676"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 4.3799999999999999
                        },
                        new
                        {
                            Id = new Guid("d36c5e35-c471-4288-b821-13a7a65ddc77"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("74b32655-e330-4e74-a1a2-e1e92023f676"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 3.29
                        },
                        new
                        {
                            Id = new Guid("5811d3fb-c83d-4477-b1fd-11d4777032c2"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("74b32655-e330-4e74-a1a2-e1e92023f676"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 2.1899999999999999
                        },
                        new
                        {
                            Id = new Guid("87d5322d-59a3-4bdf-a807-70b02fea9a72"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("74b32655-e330-4e74-a1a2-e1e92023f676"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 1.1000000000000001
                        },
                        new
                        {
                            Id = new Guid("dc7112c5-e23e-494d-be53-f22f2e6ebecf"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("74b32655-e330-4e74-a1a2-e1e92023f676"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("579c23a8-ebd6-4b50-8c13-9d9376df4ef3"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("c69edb03-4fb6-4071-bcc5-f158808c69ee"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 7.7999999999999998
                        },
                        new
                        {
                            Id = new Guid("f917d1ad-68db-4a28-b05d-5d8edcc53a1c"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("c69edb03-4fb6-4071-bcc5-f158808c69ee"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 6.2400000000000002
                        },
                        new
                        {
                            Id = new Guid("ac412ebc-2947-4e95-9836-4ee842224c4d"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("c69edb03-4fb6-4071-bcc5-f158808c69ee"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 4.6799999999999997
                        },
                        new
                        {
                            Id = new Guid("530dfdea-5921-4428-8380-3b6731220a23"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("c69edb03-4fb6-4071-bcc5-f158808c69ee"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 3.1200000000000001
                        },
                        new
                        {
                            Id = new Guid("cf2c5ac2-94d7-427c-af2b-0e8305d841bb"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("c69edb03-4fb6-4071-bcc5-f158808c69ee"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 1.5600000000000001
                        },
                        new
                        {
                            Id = new Guid("39152f1c-6366-43ca-90cb-58d1e5f6b59a"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("c69edb03-4fb6-4071-bcc5-f158808c69ee"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("241b1b35-3847-4246-80b0-e300c9f6315f"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("e777b5bf-559d-4194-a711-89ca4ca4a212"),
                            FactorTypeId = new Guid("cdd64d87-bb9a-4c17-b809-05c4454e6998"),
                            Value = 7.0
                        },
                        new
                        {
                            Id = new Guid("d2f9d59f-af3b-4d33-b936-ac8d83b9f0af"),
                            DifficultyLevelId = new Guid("5540d80e-8fae-4afb-a475-b49c1a9c4c2e"),
                            FactorId = new Guid("e777b5bf-559d-4194-a711-89ca4ca4a212"),
                            FactorTypeId = new Guid("cdd64d87-bb9a-4c17-b809-05c4454e6998"),
                            Value = 10.0
                        },
                        new
                        {
                            Id = new Guid("c9d3422b-2b30-4a2c-880b-1bd9b4e2da7c"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("e777b5bf-559d-4194-a711-89ca4ca4a212"),
                            FactorTypeId = new Guid("cdd64d87-bb9a-4c17-b809-05c4454e6998"),
                            Value = 15.0
                        },
                        new
                        {
                            Id = new Guid("898a609b-41d4-4184-bdcd-17a06904dd63"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("d7c7beea-3351-482b-82e1-8df4573395b9"),
                            FactorTypeId = new Guid("cdd64d87-bb9a-4c17-b809-05c4454e6998"),
                            Value = 5.0
                        },
                        new
                        {
                            Id = new Guid("f2b33783-dddc-4338-8bd8-ba4a5519eaf0"),
                            DifficultyLevelId = new Guid("5540d80e-8fae-4afb-a475-b49c1a9c4c2e"),
                            FactorId = new Guid("d7c7beea-3351-482b-82e1-8df4573395b9"),
                            FactorTypeId = new Guid("cdd64d87-bb9a-4c17-b809-05c4454e6998"),
                            Value = 7.0
                        },
                        new
                        {
                            Id = new Guid("e115074a-9a45-4544-8ed8-03207d8f6f42"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("d7c7beea-3351-482b-82e1-8df4573395b9"),
                            FactorTypeId = new Guid("cdd64d87-bb9a-4c17-b809-05c4454e6998"),
                            Value = 10.0
                        },
                        new
                        {
                            Id = new Guid("baa096bf-ab14-49f7-a97d-ea243410beae"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("73a3a716-f447-4057-99ca-1500d438ba58"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 3.0
                        },
                        new
                        {
                            Id = new Guid("55b4aa9e-ba88-4843-ab2d-f9cafc88f5d1"),
                            DifficultyLevelId = new Guid("5540d80e-8fae-4afb-a475-b49c1a9c4c2e"),
                            FactorId = new Guid("73a3a716-f447-4057-99ca-1500d438ba58"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 4.0
                        },
                        new
                        {
                            Id = new Guid("71432403-3812-41fe-ba15-567b1e9cf13e"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("73a3a716-f447-4057-99ca-1500d438ba58"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 6.0
                        },
                        new
                        {
                            Id = new Guid("b00d8a4f-a877-4851-a568-084be27e932d"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("31f2f6d6-a5fa-4da3-adcf-0a5cc237eb95"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 4.0
                        },
                        new
                        {
                            Id = new Guid("96d67506-c906-4209-8914-abf3c70b5ed5"),
                            DifficultyLevelId = new Guid("5540d80e-8fae-4afb-a475-b49c1a9c4c2e"),
                            FactorId = new Guid("31f2f6d6-a5fa-4da3-adcf-0a5cc237eb95"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 5.0
                        },
                        new
                        {
                            Id = new Guid("2da508e5-ea4a-48cf-b678-785d8f5282ea"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("31f2f6d6-a5fa-4da3-adcf-0a5cc237eb95"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 7.0
                        },
                        new
                        {
                            Id = new Guid("03a491c3-e66d-411a-90de-25b611297f2c"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("7a540a8b-0198-40d8-9185-2e02ba5eb1ab"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 3.0
                        },
                        new
                        {
                            Id = new Guid("cf4b205e-2b33-4a56-8cef-73f3135a8a91"),
                            DifficultyLevelId = new Guid("5540d80e-8fae-4afb-a475-b49c1a9c4c2e"),
                            FactorId = new Guid("7a540a8b-0198-40d8-9185-2e02ba5eb1ab"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 4.0
                        },
                        new
                        {
                            Id = new Guid("25601fec-bb22-4d24-a254-fb4c7eeded1b"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("7a540a8b-0198-40d8-9185-2e02ba5eb1ab"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 6.0
                        });
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.EvaluationAttributes.EvaluationAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FactorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FactorTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EvaluationAttributes");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Evaluator.Evaluator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Evaluators");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.EvaluatorToEvaluatedFactor.EvaluatorToEvaluatedFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluatedFactorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluatorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatedFactorId");

                    b.HasIndex("EvaluatorId");

                    b.ToTable("EvaluatorToEvaluatedFactors");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.FactorType.FactorType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FactorTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Name = "Influence factor"
                        },
                        new
                        {
                            Id = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Name = "Scale factor"
                        },
                        new
                        {
                            Id = new Guid("cdd64d87-bb9a-4c17-b809-05c4454e6998"),
                            Name = "Information object"
                        },
                        new
                        {
                            Id = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Name = "Function"
                        });
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Profile.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("EvaluatorId");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramLanguage.ProgramLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SLOC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProgramLanguages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c83b88ea-8f9f-4cbf-8571-8ab96cac7f40"),
                            Name = "ABAP (SAP)",
                            SLOC = 28
                        },
                        new
                        {
                            Id = new Guid("f99c3260-307d-4853-b54e-97d682b6b76a"),
                            Name = "ASP",
                            SLOC = 51
                        },
                        new
                        {
                            Id = new Guid("6e09115c-3462-4a80-aa48-2fab7c2c2460"),
                            Name = "Assembler",
                            SLOC = 119
                        },
                        new
                        {
                            Id = new Guid("1e9241d5-be6a-4907-a494-8267098bfa79"),
                            Name = "Brio +",
                            SLOC = 14
                        },
                        new
                        {
                            Id = new Guid("20a2f1a9-2acd-49c3-99ec-c0861c3b505a"),
                            Name = "C",
                            SLOC = 97
                        },
                        new
                        {
                            Id = new Guid("14b43065-db4a-42f0-9829-db0a3fcb654e"),
                            Name = "C++",
                            SLOC = 50
                        },
                        new
                        {
                            Id = new Guid("e11e7c0d-cf96-42ac-98ae-0a0b97cb409c"),
                            Name = "C#",
                            SLOC = 54
                        },
                        new
                        {
                            Id = new Guid("9bd32031-7b66-4013-8d47-01fa8ae88cba"),
                            Name = "COBOL",
                            SLOC = 61
                        },
                        new
                        {
                            Id = new Guid("4fc6d47f-b3be-41e6-98dd-fe4ac07fd9ea"),
                            Name = "Cognos Impromptu Scripts +",
                            SLOC = 47
                        },
                        new
                        {
                            Id = new Guid("d133b1e5-e6bc-4381-991c-508d69dd79a4"),
                            Name = "Cross System Products (CSP) +",
                            SLOC = 20
                        },
                        new
                        {
                            Id = new Guid("b2a445af-e803-4662-92f3-75e59b39a2a9"),
                            Name = "Cool:Gen/IEF",
                            SLOC = 32
                        },
                        new
                        {
                            Id = new Guid("f88bcd6b-a6fe-4894-a616-640d8b9bf221"),
                            Name = "Datastage",
                            SLOC = 71
                        },
                        new
                        {
                            Id = new Guid("2ddf1d2e-06cb-415f-8a77-1e470646980e"),
                            Name = "Excel",
                            SLOC = 209
                        },
                        new
                        {
                            Id = new Guid("8ed91646-4b2b-44cd-ae59-6b89a002f8c0"),
                            Name = "Focus",
                            SLOC = 43
                        },
                        new
                        {
                            Id = new Guid("47a0c764-c554-4db9-8b94-484af14f3cf7"),
                            Name = "FoxPro",
                            SLOC = 36
                        },
                        new
                        {
                            Id = new Guid("fafd2d6d-e5e1-4639-a266-73232a7a6db2"),
                            Name = "HTML",
                            SLOC = 34
                        },
                        new
                        {
                            Id = new Guid("67280c7b-08bf-4a9b-9c1f-af5c36f6a0e0"),
                            Name = "J2EE",
                            SLOC = 46
                        },
                        new
                        {
                            Id = new Guid("78e4eb50-3e6b-4417-953d-df5271f44295"),
                            Name = "Java",
                            SLOC = 53
                        },
                        new
                        {
                            Id = new Guid("9ef66b34-0332-4509-b480-e74b0c1447be"),
                            Name = "JavaScript",
                            SLOC = 47
                        },
                        new
                        {
                            Id = new Guid("bf186236-931a-4e09-9630-6896ecb9a8f6"),
                            Name = "JCL",
                            SLOC = 62
                        },
                        new
                        {
                            Id = new Guid("243ce039-e727-402f-b68f-9e1cc15f4d6a"),
                            Name = "LINC II",
                            SLOC = 29
                        },
                        new
                        {
                            Id = new Guid("fd846b36-960c-4901-a3b7-eff6e126f985"),
                            Name = "Lotus Notes",
                            SLOC = 23
                        },
                        new
                        {
                            Id = new Guid("84e88afe-e621-440e-b7f3-2f7745cd30c2"),
                            Name = "Natural",
                            SLOC = 40
                        },
                        new
                        {
                            Id = new Guid("a8cfd087-2211-4fc8-9053-4e8e0999e0a7"),
                            Name = ".NET",
                            SLOC = 57
                        },
                        new
                        {
                            Id = new Guid("eebfc4b7-8374-404b-98f0-653b491b877e"),
                            Name = "Oracle",
                            SLOC = 37
                        });
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramsParametr.ProgramsParametr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProgramLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ProgramLanguageId");

                    b.ToTable("ProgramsParametrs");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramsParametrToSubjectAreaElement.ProgramsParametrToSubjectAreaElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProgramsParametrId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectAreaElementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProgramsParametrId");

                    b.HasIndex("SubjectAreaElementId");

                    b.ToTable("ProgramsParametrToSubjectAreaElements");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Application.Application", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Evaluator.Evaluator", "Creator")
                        .WithMany("Applications")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ApplicationToEvaluator.ApplicationToEvaluator", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Application.Application", "Application")
                        .WithMany("ApplicationToEvaluators")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Evaluator.Evaluator", "Evaluator")
                        .WithMany("ApplicationToEvaluators")
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Evaluator");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ApplicationToFactors.ApplicationToFactors", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Application.Application", "Application")
                        .WithMany("Factors")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.DifficultyLevelsTypeToFactorType.DifficultyLevelsTypeToFactorType", "DifficultyLevelsTypeToFactorType")
                        .WithMany("ApplicationToFactors")
                        .HasForeignKey("DifficultyLevelsTypeToFactorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("DifficultyLevelsTypeToFactorType");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Department.Department", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Department.Department", "Parent")
                        .WithMany("SubDepartments")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.DifficultyLevels.DifficultyLevel", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.EvaluationAttributes.EvaluationAttribute", null)
                        .WithMany("DifficultyLevels")
                        .HasForeignKey("EvaluationAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.DifficultyLevelsTypeToFactorType.DifficultyLevelsTypeToFactorType", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.DifficultyLevelsType.DifficultyLevelsType", "DifficultyLevel")
                        .WithMany("DifficultyLevelsTypeToFactorTypes")
                        .HasForeignKey("DifficultyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Attribute.Attribute", "Factor")
                        .WithMany("DifficultyLevelsTypeToFactorTypes")
                        .HasForeignKey("FactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.FactorType.FactorType", "FactorType")
                        .WithMany("DifficultyLevelsTypeToFactorTypes")
                        .HasForeignKey("FactorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DifficultyLevel");

                    b.Navigation("Factor");

                    b.Navigation("FactorType");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Evaluator.Evaluator", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Department.Department", "Department")
                        .WithMany("Evaluators")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.EvaluatorToEvaluatedFactor.EvaluatorToEvaluatedFactor", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ApplicationToFactors.ApplicationToFactors", "EvaluatedFactor")
                        .WithMany("EvaluatorToEvaluatedFactor")
                        .HasForeignKey("EvaluatedFactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Evaluator.Evaluator", "Evaluator")
                        .WithMany("EvaluatorToEvaluatedFactor")
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluatedFactor");

                    b.Navigation("Evaluator");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Profile.Profile", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Attribute.Attribute", "Attribute")
                        .WithMany("Profiles")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Evaluator.Evaluator", "Evaluator")
                        .WithMany("Profiles")
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Evaluator");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramsParametr.ProgramsParametr", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Application.Application", "Application")
                        .WithMany("ProgramsParametrs")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramLanguage.ProgramLanguage", "ProgramLanguage")
                        .WithMany("ProgramsParametrs")
                        .HasForeignKey("ProgramLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("ProgramLanguage");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramsParametrToSubjectAreaElement.ProgramsParametrToSubjectAreaElement", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramsParametr.ProgramsParametr", "ProgramsParametr")
                        .WithMany("ProgramsParametrToSubjectAreaElements")
                        .HasForeignKey("ProgramsParametrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ApplicationToFactors.ApplicationToFactors", "SubjectAreaElement")
                        .WithMany("ProgramsParametrToSubjectAreaElements")
                        .HasForeignKey("SubjectAreaElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramsParametr");

                    b.Navigation("SubjectAreaElement");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Application.Application", b =>
                {
                    b.Navigation("ApplicationToEvaluators");

                    b.Navigation("Factors");

                    b.Navigation("ProgramsParametrs");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ApplicationToFactors.ApplicationToFactors", b =>
                {
                    b.Navigation("EvaluatorToEvaluatedFactor");

                    b.Navigation("ProgramsParametrToSubjectAreaElements");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Attribute.Attribute", b =>
                {
                    b.Navigation("DifficultyLevelsTypeToFactorTypes");

                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Department.Department", b =>
                {
                    b.Navigation("Evaluators");

                    b.Navigation("SubDepartments");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.DifficultyLevelsType.DifficultyLevelsType", b =>
                {
                    b.Navigation("DifficultyLevelsTypeToFactorTypes");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.DifficultyLevelsTypeToFactorType.DifficultyLevelsTypeToFactorType", b =>
                {
                    b.Navigation("ApplicationToFactors");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.EvaluationAttributes.EvaluationAttribute", b =>
                {
                    b.Navigation("DifficultyLevels");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Evaluator.Evaluator", b =>
                {
                    b.Navigation("ApplicationToEvaluators");

                    b.Navigation("Applications");

                    b.Navigation("EvaluatorToEvaluatedFactor");

                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.FactorType.FactorType", b =>
                {
                    b.Navigation("DifficultyLevelsTypeToFactorTypes");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramLanguage.ProgramLanguage", b =>
                {
                    b.Navigation("ProgramsParametrs");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramsParametr.ProgramsParametr", b =>
                {
                    b.Navigation("ProgramsParametrToSubjectAreaElements");
                });
#pragma warning restore 612, 618
        }
    }
}
