// <auto-generated />
using ITProjectPriceCalculationManager.ITProjectsManager.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace ITProjectPriceCalculationManager.ITProjectsManager.API.Migrations
{
    [DbContext(typeof(ITProjectPriceCalculationManagerDbContext))]
    partial class ITProjectPriceCalculationManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Application.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AverageCostLabor")
                        .HasColumnType("float");

                    b.Property<double>("AverageMonthlyRateWorkingHours")
                        .HasColumnType("float");

                    b.Property<double?>("ConfidenceArea")
                        .HasColumnType("float");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Overhead")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Profit")
                        .HasColumnType("float");

                    b.Property<double>("SocialInsurance")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ApplicationToEvaluator.ApplicationToEvaluator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("SelfEvaluation")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("EvaluatorId");

                    b.ToTable("ApplicationToEvaluators");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ApplicationToFactors.ApplicationToFactors", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DifficultyLevelsTypeToFactorTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("DifficultyLevelsTypeToFactorTypeId");

                    b.ToTable("ApplicationToFactors");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Attribute.Attribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Attributes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a0822a4-7012-4738-889b-fafb713f72ea"),
                            Name = "Qualifications(PERS)"
                        },
                        new
                        {
                            Id = new Guid("24fbf4f3-aa84-4b17-9d2e-0ef16238a2ba"),
                            Name = "Experience(PREX)"
                        },
                        new
                        {
                            Id = new Guid("33e07ded-1bd4-4e9a-8076-f071ea1a5269"),
                            Name = "Technical support(FCIL)"
                        },
                        new
                        {
                            Id = new Guid("ea5a8d97-0940-4463-b07a-d6a10b6f0d08"),
                            Name = "Schedule restrictions(SCED)"
                        },
                        new
                        {
                            Id = new Guid("fe85d6ab-ade6-412f-b2a6-7ca97f4f1da4"),
                            Name = "Complexity of the program environment(PDIF)"
                        },
                        new
                        {
                            Id = new Guid("4feab03a-7415-4c72-8b3f-6901e014c25e"),
                            Name = "Complexity and reliability(RCPX)"
                        },
                        new
                        {
                            Id = new Guid("9b7d2f14-9ec0-414c-806b-d5e607664031"),
                            Name = "Reuse requested(RUSE)"
                        },
                        new
                        {
                            Id = new Guid("15140cfd-eacc-41f3-aae5-718980da88b9"),
                            Name = "Product novelty for the developer's company(PREC)"
                        },
                        new
                        {
                            Id = new Guid("b4a2b0b2-35c4-41d4-8ca7-1d2ebd1440e9"),
                            Name = "Development flexibility(FLEX)"
                        },
                        new
                        {
                            Id = new Guid("186476d2-772b-4eb1-b140-b0c1a238ae11"),
                            Name = "Level of risk/architecture management (%)(RESL)"
                        },
                        new
                        {
                            Id = new Guid("74b32655-e330-4e74-a1a2-e1e92023f676"),
                            Name = "Cohesion of the development team(TEAM)"
                        },
                        new
                        {
                            Id = new Guid("c69edb03-4fb6-4071-bcc5-f158808c69ee"),
                            Name = "Technology maturity maturity process development(PMAT)"
                        },
                        new
                        {
                            Id = new Guid("e777b5bf-559d-4194-a711-89ca4ca4a212"),
                            Name = "Internal logical object"
                        },
                        new
                        {
                            Id = new Guid("d7c7beea-3351-482b-82e1-8df4573395b9"),
                            Name = "External interface object"
                        },
                        new
                        {
                            Id = new Guid("73a3a716-f447-4057-99ca-1500d438ba58"),
                            Name = "External input"
                        },
                        new
                        {
                            Id = new Guid("31f2f6d6-a5fa-4da3-adcf-0a5cc237eb95"),
                            Name = "External output"
                        },
                        new
                        {
                            Id = new Guid("7a540a8b-0198-40d8-9185-2e02ba5eb1ab"),
                            Name = "External request"
                        });
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Department.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.DifficultyLevelsType.DifficultyLevelsType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DifficultyLevelsTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3b0177d-baf9-4ad6-b1c1-002e1b776a10"),
                            Name = "Super low"
                        },
                        new
                        {
                            Id = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            Name = "Very low"
                        },
                        new
                        {
                            Id = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            Name = "Low"
                        },
                        new
                        {
                            Id = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            Name = "Normal"
                        },
                        new
                        {
                            Id = new Guid("5540d80e-8fae-4afb-a475-b49c1a9c4c2e"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            Name = "High"
                        },
                        new
                        {
                            Id = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            Name = "Very high"
                        },
                        new
                        {
                            Id = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            Name = "Super high"
                        });
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.DifficultyLevelsTypeToFactorType.DifficultyLevelsTypeToFactorType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DifficultyLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FactorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FactorTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyLevelId");

                    b.HasIndex("FactorId");

                    b.HasIndex("FactorTypeId");

                    b.ToTable("DifficultyLevelsTypeToFactorTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74a0e6ef-956a-4b55-bbc2-134f38797a34"),
                            DifficultyLevelId = new Guid("b3b0177d-baf9-4ad6-b1c1-002e1b776a10"),
                            FactorId = new Guid("7a0822a4-7012-4738-889b-fafb713f72ea"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 2.1200000000000001
                        },
                        new
                        {
                            Id = new Guid("b2f1d8aa-0f39-42a3-97e3-a235da3ba0f6"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("7a0822a4-7012-4738-889b-fafb713f72ea"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.6200000000000001
                        },
                        new
                        {
                            Id = new Guid("c4662ee7-17de-46da-aae3-1c5d217715e0"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("7a0822a4-7012-4738-889b-fafb713f72ea"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.26
                        },
                        new
                        {
                            Id = new Guid("0f80045c-b619-4d33-9ea4-62c596871929"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("7a0822a4-7012-4738-889b-fafb713f72ea"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("08928ccf-e731-4201-963f-38bce1d3054c"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("7a0822a4-7012-4738-889b-fafb713f72ea"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.82999999999999996
                        },
                        new
                        {
                            Id = new Guid("7f56875e-20f8-4e25-9cf1-2a9d5e1b2bf0"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("7a0822a4-7012-4738-889b-fafb713f72ea"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.63
                        },
                        new
                        {
                            Id = new Guid("080334d8-5963-4cc0-8136-9191bccda028"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("7a0822a4-7012-4738-889b-fafb713f72ea"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.5
                        },
                        new
                        {
                            Id = new Guid("5ee31be2-ae73-4007-843a-6fb8b039b934"),
                            DifficultyLevelId = new Guid("b3b0177d-baf9-4ad6-b1c1-002e1b776a10"),
                            FactorId = new Guid("24fbf4f3-aa84-4b17-9d2e-0ef16238a2ba"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.5900000000000001
                        },
                        new
                        {
                            Id = new Guid("b18385d9-e24f-4ba7-8263-8ca596a73e7c"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("24fbf4f3-aa84-4b17-9d2e-0ef16238a2ba"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.3300000000000001
                        },
                        new
                        {
                            Id = new Guid("9ec148f0-93b4-41e1-829c-cada31069593"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("24fbf4f3-aa84-4b17-9d2e-0ef16238a2ba"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.1200000000000001
                        },
                        new
                        {
                            Id = new Guid("344562dd-eefc-4fb8-ab5a-09b49499c106"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("24fbf4f3-aa84-4b17-9d2e-0ef16238a2ba"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("22012480-5e1e-42db-80ba-9b181ffa2cc5"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("24fbf4f3-aa84-4b17-9d2e-0ef16238a2ba"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.87
                        },
                        new
                        {
                            Id = new Guid("e0bacc06-d484-4fe2-95aa-2cee39a9d876"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("24fbf4f3-aa84-4b17-9d2e-0ef16238a2ba"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.70999999999999996
                        },
                        new
                        {
                            Id = new Guid("b717a230-6f6f-4920-8575-3eb54712fe83"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("24fbf4f3-aa84-4b17-9d2e-0ef16238a2ba"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.62
                        },
                        new
                        {
                            Id = new Guid("ea47626b-19b5-446d-b70a-d2e5c010c60a"),
                            DifficultyLevelId = new Guid("b3b0177d-baf9-4ad6-b1c1-002e1b776a10"),
                            FactorId = new Guid("33e07ded-1bd4-4e9a-8076-f071ea1a5269"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.4299999999999999
                        },
                        new
                        {
                            Id = new Guid("f5b54f9b-3976-4de6-a092-3beeb39d1e38"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("33e07ded-1bd4-4e9a-8076-f071ea1a5269"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.3
                        },
                        new
                        {
                            Id = new Guid("0b95246c-3275-4bee-b6f9-9538b86c5370"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("33e07ded-1bd4-4e9a-8076-f071ea1a5269"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.1000000000000001
                        },
                        new
                        {
                            Id = new Guid("b2f75934-8004-48dd-8f5f-a8bae288efb6"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("33e07ded-1bd4-4e9a-8076-f071ea1a5269"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("8cc17c64-28ae-48c0-bc49-5a93a768aff6"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("33e07ded-1bd4-4e9a-8076-f071ea1a5269"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.87
                        },
                        new
                        {
                            Id = new Guid("97ce6162-8461-4291-af11-8b522a1545c9"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("33e07ded-1bd4-4e9a-8076-f071ea1a5269"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.72999999999999998
                        },
                        new
                        {
                            Id = new Guid("1f33720d-dcff-4ecc-be50-e77638689458"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("33e07ded-1bd4-4e9a-8076-f071ea1a5269"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.62
                        },
                        new
                        {
                            Id = new Guid("b3b7a1e0-0112-422b-a09a-72c7ae2044b7"),
                            DifficultyLevelId = new Guid("b3b0177d-baf9-4ad6-b1c1-002e1b776a10"),
                            FactorId = new Guid("ea5a8d97-0940-4463-b07a-d6a10b6f0d08"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("a6cbff94-1d4c-4150-b7ae-e8c0ccde7c40"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("ea5a8d97-0940-4463-b07a-d6a10b6f0d08"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.4299999999999999
                        },
                        new
                        {
                            Id = new Guid("4ea4d568-5b28-4274-a1d8-11c7155aaef0"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("ea5a8d97-0940-4463-b07a-d6a10b6f0d08"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.1399999999999999
                        },
                        new
                        {
                            Id = new Guid("42d9cce8-9d09-4ce0-bf87-5fab99001744"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("ea5a8d97-0940-4463-b07a-d6a10b6f0d08"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("3fdab9d5-6656-498c-ac9d-a7549432c663"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("ea5a8d97-0940-4463-b07a-d6a10b6f0d08"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("0c5990e1-f1ce-4110-81ec-348a1c913070"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("ea5a8d97-0940-4463-b07a-d6a10b6f0d08"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("0b2d5fe7-d297-4c07-a703-467fafb487d3"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("ea5a8d97-0940-4463-b07a-d6a10b6f0d08"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("df171536-ed65-44a6-8afd-8a8bc67cef5e"),
                            DifficultyLevelId = new Guid("b3b0177d-baf9-4ad6-b1c1-002e1b776a10"),
                            FactorId = new Guid("fe85d6ab-ade6-412f-b2a6-7ca97f4f1da4"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("76fc4f6c-6e64-4a5b-add8-b26a95658cd2"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("fe85d6ab-ade6-412f-b2a6-7ca97f4f1da4"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("c17d7e59-ad2f-4f61-8b13-011545443617"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("fe85d6ab-ade6-412f-b2a6-7ca97f4f1da4"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.87
                        },
                        new
                        {
                            Id = new Guid("fb237587-b7ed-4f7c-93fa-c7f169a407be"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("fe85d6ab-ade6-412f-b2a6-7ca97f4f1da4"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("66447184-6da6-4024-8647-fb28d8679056"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("fe85d6ab-ade6-412f-b2a6-7ca97f4f1da4"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.29
                        },
                        new
                        {
                            Id = new Guid("9f69a437-f98c-439e-a6d5-f0ac0d55e5d1"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("fe85d6ab-ade6-412f-b2a6-7ca97f4f1da4"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.8100000000000001
                        },
                        new
                        {
                            Id = new Guid("2facf71e-b943-4d21-9faf-1434f5ccf8bf"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("fe85d6ab-ade6-412f-b2a6-7ca97f4f1da4"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 2.6099999999999999
                        },
                        new
                        {
                            Id = new Guid("0e414147-fa7f-4858-b6a5-63efb2d17261"),
                            DifficultyLevelId = new Guid("b3b0177d-baf9-4ad6-b1c1-002e1b776a10"),
                            FactorId = new Guid("4feab03a-7415-4c72-8b3f-6901e014c25e"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.48999999999999999
                        },
                        new
                        {
                            Id = new Guid("06847fef-03c2-43a3-ac5b-2c614ee57cf6"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("4feab03a-7415-4c72-8b3f-6901e014c25e"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.59999999999999998
                        },
                        new
                        {
                            Id = new Guid("cdf53dd1-5e38-4b77-b71e-cd3704b81364"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("4feab03a-7415-4c72-8b3f-6901e014c25e"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.82999999999999996
                        },
                        new
                        {
                            Id = new Guid("9d55abdd-293c-4a93-9e1b-937fee3371de"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("4feab03a-7415-4c72-8b3f-6901e014c25e"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("5e91441b-4c30-4c75-904f-d1f9e50da5e9"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("4feab03a-7415-4c72-8b3f-6901e014c25e"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.3300000000000001
                        },
                        new
                        {
                            Id = new Guid("d3244fa5-20f9-47b5-be22-3b74cd94ed2b"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("4feab03a-7415-4c72-8b3f-6901e014c25e"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.97
                        },
                        new
                        {
                            Id = new Guid("769ddae9-c118-4ea9-a897-15b8866bfbdf"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("4feab03a-7415-4c72-8b3f-6901e014c25e"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 2.7200000000000002
                        },
                        new
                        {
                            Id = new Guid("25ecde11-9402-4c13-90d6-41c78275f6fd"),
                            DifficultyLevelId = new Guid("b3b0177d-baf9-4ad6-b1c1-002e1b776a10"),
                            FactorId = new Guid("9b7d2f14-9ec0-414c-806b-d5e607664031"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("9e02cb9a-4f14-49d6-9643-37fe8adb84a4"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("9b7d2f14-9ec0-414c-806b-d5e607664031"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("fd34903c-2514-4955-ae4d-cdf134964d8c"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("9b7d2f14-9ec0-414c-806b-d5e607664031"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 0.94999999999999996
                        },
                        new
                        {
                            Id = new Guid("01445c8b-0a85-4545-a66c-0751ef3293d1"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("9b7d2f14-9ec0-414c-806b-d5e607664031"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0
                        },
                        new
                        {
                            Id = new Guid("9bec3c1e-b3d9-4f1d-839b-a37755e2e0d3"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("9b7d2f14-9ec0-414c-806b-d5e607664031"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.0700000000000001
                        },
                        new
                        {
                            Id = new Guid("33a2c308-2e6a-45d1-a2ef-b51944433733"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("9b7d2f14-9ec0-414c-806b-d5e607664031"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.1499999999999999
                        },
                        new
                        {
                            Id = new Guid("db6112be-23bb-46c4-ac1f-22618ad3b1d3"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("9b7d2f14-9ec0-414c-806b-d5e607664031"),
                            FactorTypeId = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Value = 1.24
                        },
                        new
                        {
                            Id = new Guid("4a51490b-fb60-4186-b9cb-401664cc5359"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("15140cfd-eacc-41f3-aae5-718980da88b9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 6.2000000000000002
                        },
                        new
                        {
                            Id = new Guid("92ab395c-604f-4d64-b0ae-120c61629085"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("15140cfd-eacc-41f3-aae5-718980da88b9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 4.96
                        },
                        new
                        {
                            Id = new Guid("b131e69e-648c-4126-827e-939feec92e26"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("15140cfd-eacc-41f3-aae5-718980da88b9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 3.7200000000000002
                        },
                        new
                        {
                            Id = new Guid("17b3a936-e4da-4bc9-afa3-e159a25e5265"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("15140cfd-eacc-41f3-aae5-718980da88b9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 2.48
                        },
                        new
                        {
                            Id = new Guid("c5f45485-b3e1-477a-9e5b-af92a26c901d"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("15140cfd-eacc-41f3-aae5-718980da88b9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 1.24
                        },
                        new
                        {
                            Id = new Guid("b244e563-d299-44cb-8ffc-28ecadb13233"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("15140cfd-eacc-41f3-aae5-718980da88b9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("2fa06ea7-a37c-4866-81ae-1a2613659b51"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("b4a2b0b2-35c4-41d4-8ca7-1d2ebd1440e9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 5.0700000000000003
                        },
                        new
                        {
                            Id = new Guid("09a3f26e-e28c-4e78-aa1e-b49305996894"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("b4a2b0b2-35c4-41d4-8ca7-1d2ebd1440e9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 4.0499999999999998
                        },
                        new
                        {
                            Id = new Guid("09f0e38e-7f76-48e8-9f42-543d75ce84dd"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("b4a2b0b2-35c4-41d4-8ca7-1d2ebd1440e9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 3.04
                        },
                        new
                        {
                            Id = new Guid("010a62bb-1da1-47af-b61d-90abad7578eb"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("b4a2b0b2-35c4-41d4-8ca7-1d2ebd1440e9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 2.0299999999999998
                        },
                        new
                        {
                            Id = new Guid("a52c9042-0863-40da-b02f-dd3b5b67726a"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("b4a2b0b2-35c4-41d4-8ca7-1d2ebd1440e9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 1.01
                        },
                        new
                        {
                            Id = new Guid("3a997e56-7155-41af-aa31-09cdbec6480c"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("b4a2b0b2-35c4-41d4-8ca7-1d2ebd1440e9"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("d6d3f87c-0314-4ab5-8a8e-e9087d8b1c31"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("186476d2-772b-4eb1-b140-b0c1a238ae11"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 7.0700000000000003
                        },
                        new
                        {
                            Id = new Guid("c6836473-1462-4378-89e6-30115aa853d8"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("186476d2-772b-4eb1-b140-b0c1a238ae11"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 5.6500000000000004
                        },
                        new
                        {
                            Id = new Guid("1aa8fc7f-75c2-4f89-87f8-cf1f734df5ee"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("186476d2-772b-4eb1-b140-b0c1a238ae11"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 4.2400000000000002
                        },
                        new
                        {
                            Id = new Guid("aea67f51-78f5-466b-a80a-c965ba3f45c7"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("186476d2-772b-4eb1-b140-b0c1a238ae11"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 2.8300000000000001
                        },
                        new
                        {
                            Id = new Guid("f1513fd1-7c0c-4725-9495-11b72bcd40d1"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("186476d2-772b-4eb1-b140-b0c1a238ae11"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 1.4099999999999999
                        },
                        new
                        {
                            Id = new Guid("8f6a807a-5288-4f09-bbf6-1e40216cd297"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("186476d2-772b-4eb1-b140-b0c1a238ae11"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("998fb1a6-04f7-47c2-ab81-db106f0b7889"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("74b32655-e330-4e74-a1a2-e1e92023f676"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 5.4800000000000004
                        },
                        new
                        {
                            Id = new Guid("3cf106e7-95ff-41a7-ad8f-65726958e65c"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("74b32655-e330-4e74-a1a2-e1e92023f676"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 4.3799999999999999
                        },
                        new
                        {
                            Id = new Guid("09c3a9d1-5e20-46e8-9705-0a5f8a027df3"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("74b32655-e330-4e74-a1a2-e1e92023f676"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 3.29
                        },
                        new
                        {
                            Id = new Guid("531788ef-d484-4e01-85d1-e7029f24eb0a"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("74b32655-e330-4e74-a1a2-e1e92023f676"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 2.1899999999999999
                        },
                        new
                        {
                            Id = new Guid("2d31d1ce-49a8-4914-a403-437114976658"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("74b32655-e330-4e74-a1a2-e1e92023f676"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 1.1000000000000001
                        },
                        new
                        {
                            Id = new Guid("dde0fdce-ce79-49b1-9b5f-564cd48eb73e"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("74b32655-e330-4e74-a1a2-e1e92023f676"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("c1adcabb-39e9-4fb9-8059-af933bd9e710"),
                            DifficultyLevelId = new Guid("0c5fd362-b14d-4186-bef9-979ed21b9575"),
                            FactorId = new Guid("c69edb03-4fb6-4071-bcc5-f158808c69ee"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 7.7999999999999998
                        },
                        new
                        {
                            Id = new Guid("52e0df58-2d52-41d4-bf64-d64e631b12f0"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("c69edb03-4fb6-4071-bcc5-f158808c69ee"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 6.2400000000000002
                        },
                        new
                        {
                            Id = new Guid("332d7f7d-c836-44e6-8865-eeaed7cd3831"),
                            DifficultyLevelId = new Guid("b29fa523-bd56-48be-9adc-cbd23f0af646"),
                            FactorId = new Guid("c69edb03-4fb6-4071-bcc5-f158808c69ee"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 4.6799999999999997
                        },
                        new
                        {
                            Id = new Guid("37a116ea-82dc-4853-95d5-5fcd2b06e37e"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("c69edb03-4fb6-4071-bcc5-f158808c69ee"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 3.1200000000000001
                        },
                        new
                        {
                            Id = new Guid("aaa0cb06-3c13-4267-83c9-68e5446b21a1"),
                            DifficultyLevelId = new Guid("f5ad4a31-a240-41bd-bffd-245103b88d0f"),
                            FactorId = new Guid("c69edb03-4fb6-4071-bcc5-f158808c69ee"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 1.5600000000000001
                        },
                        new
                        {
                            Id = new Guid("00ea34c1-172f-4d5a-a2f1-458322fe4561"),
                            DifficultyLevelId = new Guid("c15c008f-f7f4-4dae-95bb-02a32bb2b8b1"),
                            FactorId = new Guid("c69edb03-4fb6-4071-bcc5-f158808c69ee"),
                            FactorTypeId = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("077409d6-1c6a-43e9-a241-5612d0db1e31"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("e777b5bf-559d-4194-a711-89ca4ca4a212"),
                            FactorTypeId = new Guid("cdd64d87-bb9a-4c17-b809-05c4454e6998"),
                            Value = 7.0
                        },
                        new
                        {
                            Id = new Guid("651f4541-a573-4d2d-b51f-c7f88acb6164"),
                            DifficultyLevelId = new Guid("5540d80e-8fae-4afb-a475-b49c1a9c4c2e"),
                            FactorId = new Guid("e777b5bf-559d-4194-a711-89ca4ca4a212"),
                            FactorTypeId = new Guid("cdd64d87-bb9a-4c17-b809-05c4454e6998"),
                            Value = 10.0
                        },
                        new
                        {
                            Id = new Guid("6968abd1-ef92-4b58-9ab4-b538af693085"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("e777b5bf-559d-4194-a711-89ca4ca4a212"),
                            FactorTypeId = new Guid("cdd64d87-bb9a-4c17-b809-05c4454e6998"),
                            Value = 15.0
                        },
                        new
                        {
                            Id = new Guid("f3edb65a-3e63-401d-8db0-8d1dc1096a5e"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("d7c7beea-3351-482b-82e1-8df4573395b9"),
                            FactorTypeId = new Guid("cdd64d87-bb9a-4c17-b809-05c4454e6998"),
                            Value = 5.0
                        },
                        new
                        {
                            Id = new Guid("4c443311-3124-4773-ab18-8d737b09d5b3"),
                            DifficultyLevelId = new Guid("5540d80e-8fae-4afb-a475-b49c1a9c4c2e"),
                            FactorId = new Guid("d7c7beea-3351-482b-82e1-8df4573395b9"),
                            FactorTypeId = new Guid("cdd64d87-bb9a-4c17-b809-05c4454e6998"),
                            Value = 7.0
                        },
                        new
                        {
                            Id = new Guid("88df5f0f-8289-49ae-ad20-016cebd4b645"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("d7c7beea-3351-482b-82e1-8df4573395b9"),
                            FactorTypeId = new Guid("cdd64d87-bb9a-4c17-b809-05c4454e6998"),
                            Value = 10.0
                        },
                        new
                        {
                            Id = new Guid("bbc9f3e6-5fb3-4da5-81c1-b492e0c8f527"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("73a3a716-f447-4057-99ca-1500d438ba58"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 3.0
                        },
                        new
                        {
                            Id = new Guid("aeabd664-245a-441f-94d0-502111b866d8"),
                            DifficultyLevelId = new Guid("5540d80e-8fae-4afb-a475-b49c1a9c4c2e"),
                            FactorId = new Guid("73a3a716-f447-4057-99ca-1500d438ba58"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 4.0
                        },
                        new
                        {
                            Id = new Guid("6c77d151-9f75-47c2-81e8-1bf845916602"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("73a3a716-f447-4057-99ca-1500d438ba58"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 6.0
                        },
                        new
                        {
                            Id = new Guid("187c54ad-b3e7-48e1-bd23-18d6628a4976"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("31f2f6d6-a5fa-4da3-adcf-0a5cc237eb95"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 4.0
                        },
                        new
                        {
                            Id = new Guid("d8f757ae-878a-4dda-b8f1-c1a2fde5eef2"),
                            DifficultyLevelId = new Guid("5540d80e-8fae-4afb-a475-b49c1a9c4c2e"),
                            FactorId = new Guid("31f2f6d6-a5fa-4da3-adcf-0a5cc237eb95"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 5.0
                        },
                        new
                        {
                            Id = new Guid("ee5775c1-52c0-46e7-95df-e973f314f42b"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("31f2f6d6-a5fa-4da3-adcf-0a5cc237eb95"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 7.0
                        },
                        new
                        {
                            Id = new Guid("0fb577a4-eabf-43f8-a345-9892c9c3f1b9"),
                            DifficultyLevelId = new Guid("fc6ea190-24a2-42d0-b2aa-783758efa82d"),
                            FactorId = new Guid("7a540a8b-0198-40d8-9185-2e02ba5eb1ab"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 3.0
                        },
                        new
                        {
                            Id = new Guid("44c06d2d-56af-4002-bdd2-d194a283a9c8"),
                            DifficultyLevelId = new Guid("5540d80e-8fae-4afb-a475-b49c1a9c4c2e"),
                            FactorId = new Guid("7a540a8b-0198-40d8-9185-2e02ba5eb1ab"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 4.0
                        },
                        new
                        {
                            Id = new Guid("af7637e2-e950-4e23-b84b-f4e87197d502"),
                            DifficultyLevelId = new Guid("1aa2ef63-41db-4f3d-aacd-e38c7e4639ac"),
                            FactorId = new Guid("7a540a8b-0198-40d8-9185-2e02ba5eb1ab"),
                            FactorTypeId = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Value = 6.0
                        });
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Evaluator.Evaluator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Evaluators");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.EvaluatorToEvaluatedFactor.EvaluatorToEvaluatedFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluatedFactorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluatorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatedFactorId");

                    b.HasIndex("EvaluatorId");

                    b.ToTable("EvaluatorToEvaluatedFactors");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.FactorType.FactorType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FactorTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b03771e5-488a-449f-b886-19c581b63cde"),
                            Name = "Influence factor"
                        },
                        new
                        {
                            Id = new Guid("eb8f98d6-1c46-4721-9ad6-c464b9029905"),
                            Name = "Scale factor"
                        },
                        new
                        {
                            Id = new Guid("cdd64d87-bb9a-4c17-b809-05c4454e6998"),
                            Name = "Information object"
                        },
                        new
                        {
                            Id = new Guid("63715754-cdfb-4320-9c17-72648673cb4b"),
                            Name = "Function"
                        });
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Profile.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("EvaluatorId");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramLanguage.ProgramLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SLOC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProgramLanguages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("08df04d2-912b-4067-9770-83c0c0ad11f0"),
                            Name = "ABAP (SAP)",
                            SLOC = 28
                        },
                        new
                        {
                            Id = new Guid("0a07125f-c029-4ba1-a726-c8c4bfce2f95"),
                            Name = "ASP",
                            SLOC = 51
                        },
                        new
                        {
                            Id = new Guid("87022e21-e348-4baf-a2b0-6959a2a01c36"),
                            Name = "Assembler",
                            SLOC = 119
                        },
                        new
                        {
                            Id = new Guid("09573e2f-9b64-450a-89b1-a0f037a69f13"),
                            Name = "Brio +",
                            SLOC = 14
                        },
                        new
                        {
                            Id = new Guid("7a08a3fa-4afd-42b1-a35b-fd2f832f272a"),
                            Name = "C",
                            SLOC = 97
                        },
                        new
                        {
                            Id = new Guid("cb2a99c2-3117-4992-aa69-7094bdb7e6be"),
                            Name = "C++",
                            SLOC = 50
                        },
                        new
                        {
                            Id = new Guid("e459136a-de0f-4712-b522-9ae61f1804d0"),
                            Name = "C#",
                            SLOC = 54
                        },
                        new
                        {
                            Id = new Guid("574899c6-4cca-4a91-92f1-9311a1338289"),
                            Name = "COBOL",
                            SLOC = 61
                        },
                        new
                        {
                            Id = new Guid("9a95a615-cb0e-4a12-ae5c-4517a6480eba"),
                            Name = "Cognos Impromptu Scripts +",
                            SLOC = 47
                        },
                        new
                        {
                            Id = new Guid("bc893b63-a04e-448a-9b60-848eecbf39e7"),
                            Name = "Cross System Products (CSP) +",
                            SLOC = 20
                        },
                        new
                        {
                            Id = new Guid("6ae7e127-c103-4bba-acba-2447d55d6821"),
                            Name = "Cool:Gen/IEF",
                            SLOC = 32
                        },
                        new
                        {
                            Id = new Guid("70e51aed-4bc1-4b01-9f9d-2a4729eae4ba"),
                            Name = "Datastage",
                            SLOC = 71
                        },
                        new
                        {
                            Id = new Guid("e29b0792-ce69-4159-9468-bcd249a906aa"),
                            Name = "Excel",
                            SLOC = 209
                        },
                        new
                        {
                            Id = new Guid("f3a081ef-b2fc-4664-bbf5-26199dc059b1"),
                            Name = "Focus",
                            SLOC = 43
                        },
                        new
                        {
                            Id = new Guid("25834df0-a34c-4a4d-9e0c-d8509e3dddd1"),
                            Name = "FoxPro",
                            SLOC = 36
                        },
                        new
                        {
                            Id = new Guid("763e6d64-87b6-4c34-b594-954cb278db01"),
                            Name = "HTML",
                            SLOC = 34
                        },
                        new
                        {
                            Id = new Guid("1feb6b40-d349-4f0d-ae3c-31800fa6a413"),
                            Name = "J2EE",
                            SLOC = 46
                        },
                        new
                        {
                            Id = new Guid("9cf980b4-a2d9-4b8b-b6a9-689911956783"),
                            Name = "Java",
                            SLOC = 53
                        },
                        new
                        {
                            Id = new Guid("0e60e3a8-695d-4241-81b2-3ac906788a8d"),
                            Name = "JavaScript",
                            SLOC = 47
                        },
                        new
                        {
                            Id = new Guid("5a715a38-2a05-4b43-8a84-9835bf6e564d"),
                            Name = "JCL",
                            SLOC = 62
                        },
                        new
                        {
                            Id = new Guid("e1ce61f7-a7fb-4802-b6f1-aba1d29fb1a6"),
                            Name = "LINC II",
                            SLOC = 29
                        },
                        new
                        {
                            Id = new Guid("64f00e6c-edb7-4266-810f-e858873c6aa5"),
                            Name = "Lotus Notes",
                            SLOC = 23
                        },
                        new
                        {
                            Id = new Guid("52f22f29-82d8-4ce0-8d60-d1b81848a11a"),
                            Name = "Natural",
                            SLOC = 40
                        },
                        new
                        {
                            Id = new Guid("8ad8e49e-5dd0-4007-8eec-b165c947da69"),
                            Name = ".NET",
                            SLOC = 57
                        },
                        new
                        {
                            Id = new Guid("bec8b82f-f763-44b5-baae-22d46ae93185"),
                            Name = "Oracle",
                            SLOC = 37
                        });
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramsParametr.ProgramsParametr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProgramLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ProgramLanguageId");

                    b.ToTable("ProgramsParametrs");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramsParametrToSubjectAreaElement.ProgramsParametrToSubjectAreaElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProgramsParametrId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectAreaElementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProgramsParametrId");

                    b.HasIndex("SubjectAreaElementId");

                    b.ToTable("ProgramsParametrToSubjectAreaElements");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Application.Application", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Evaluator.Evaluator", "Creator")
                        .WithMany("Applications")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ApplicationToEvaluator.ApplicationToEvaluator", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Application.Application", "Application")
                        .WithMany("ApplicationToEvaluators")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Evaluator.Evaluator", "Evaluator")
                        .WithMany("ApplicationToEvaluators")
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Evaluator");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ApplicationToFactors.ApplicationToFactors", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Application.Application", "Application")
                        .WithMany("Factors")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.DifficultyLevelsTypeToFactorType.DifficultyLevelsTypeToFactorType", "DifficultyLevelsTypeToFactorType")
                        .WithMany("ApplicationToFactors")
                        .HasForeignKey("DifficultyLevelsTypeToFactorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("DifficultyLevelsTypeToFactorType");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Department.Department", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Department.Department", "Parent")
                        .WithMany("SubDepartments")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.DifficultyLevelsTypeToFactorType.DifficultyLevelsTypeToFactorType", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.DifficultyLevelsType.DifficultyLevelsType", "DifficultyLevel")
                        .WithMany("DifficultyLevelsTypeToFactorTypes")
                        .HasForeignKey("DifficultyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Attribute.Attribute", "Factor")
                        .WithMany("DifficultyLevelsTypeToFactorTypes")
                        .HasForeignKey("FactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.FactorType.FactorType", "FactorType")
                        .WithMany("DifficultyLevelsTypeToFactorTypes")
                        .HasForeignKey("FactorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DifficultyLevel");

                    b.Navigation("Factor");

                    b.Navigation("FactorType");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Evaluator.Evaluator", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Department.Department", "Department")
                        .WithMany("Evaluators")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.EvaluatorToEvaluatedFactor.EvaluatorToEvaluatedFactor", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ApplicationToFactors.ApplicationToFactors", "EvaluatedFactor")
                        .WithMany("EvaluatorToEvaluatedFactor")
                        .HasForeignKey("EvaluatedFactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Evaluator.Evaluator", "Evaluator")
                        .WithMany("EvaluatorToEvaluatedFactor")
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluatedFactor");

                    b.Navigation("Evaluator");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Profile.Profile", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Attribute.Attribute", "Attribute")
                        .WithMany("Profiles")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Evaluator.Evaluator", "Evaluator")
                        .WithMany("Profiles")
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Evaluator");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramsParametr.ProgramsParametr", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Application.Application", "Application")
                        .WithMany("ProgramsParametrs")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramLanguage.ProgramLanguage", "ProgramLanguage")
                        .WithMany("ProgramsParametrs")
                        .HasForeignKey("ProgramLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("ProgramLanguage");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramsParametrToSubjectAreaElement.ProgramsParametrToSubjectAreaElement", b =>
                {
                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramsParametr.ProgramsParametr", "ProgramsParametr")
                        .WithMany("ProgramsParametrToSubjectAreaElements")
                        .HasForeignKey("ProgramsParametrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ApplicationToFactors.ApplicationToFactors", "SubjectAreaElement")
                        .WithMany("ProgramsParametrToSubjectAreaElements")
                        .HasForeignKey("SubjectAreaElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramsParametr");

                    b.Navigation("SubjectAreaElement");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Application.Application", b =>
                {
                    b.Navigation("ApplicationToEvaluators");

                    b.Navigation("Factors");

                    b.Navigation("ProgramsParametrs");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ApplicationToFactors.ApplicationToFactors", b =>
                {
                    b.Navigation("EvaluatorToEvaluatedFactor");

                    b.Navigation("ProgramsParametrToSubjectAreaElements");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Attribute.Attribute", b =>
                {
                    b.Navigation("DifficultyLevelsTypeToFactorTypes");

                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Department.Department", b =>
                {
                    b.Navigation("Evaluators");

                    b.Navigation("SubDepartments");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.DifficultyLevelsType.DifficultyLevelsType", b =>
                {
                    b.Navigation("DifficultyLevelsTypeToFactorTypes");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.DifficultyLevelsTypeToFactorType.DifficultyLevelsTypeToFactorType", b =>
                {
                    b.Navigation("ApplicationToFactors");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.Evaluator.Evaluator", b =>
                {
                    b.Navigation("ApplicationToEvaluators");

                    b.Navigation("Applications");

                    b.Navigation("EvaluatorToEvaluatedFactor");

                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.FactorType.FactorType", b =>
                {
                    b.Navigation("DifficultyLevelsTypeToFactorTypes");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramLanguage.ProgramLanguage", b =>
                {
                    b.Navigation("ProgramsParametrs");
                });

            modelBuilder.Entity("ITProjectPriceCalculationManager.ITProjectsManager.API.Core.Entities.ProgramsParametr.ProgramsParametr", b =>
                {
                    b.Navigation("ProgramsParametrToSubjectAreaElements");
                });
#pragma warning restore 612, 618
        }
    }
}
