name: CI

on:
  push:
    branches: [ main, feat/** ]
  pull_request:
    branches: [ main ]

jobs:
  build_dotnet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dotnet
        uses: actions/checkout@v3
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: 6.x.x
      
      - name: Restore
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore
    
  build_angular:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout angular
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
            
      - name: Install NPM Modules
        run: |
          cd ./ITProjectPriceCalculationManager.WebApp
          npm install

      - name: Build Project
        run: |
          cd ./ITProjectPriceCalculationManager.WebApp
          npm run build

  build_python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Python
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./ITProjectPriceCalculationManager.PricePredictor.API/requirements

  build_docker:
    runs-on: ubuntu-latest
    needs: [build_angular, build_dotnet, build_python]

    steps:
      - name: Checkout docker
        uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
